### PR TITLE
Attempted to add myself as the second best contributor and failed

### PR DESCRIPTION
**Pull request by JustDoom**
Im just better

### CODE REVIEW

**Review by TodePond — CHANGES_REQUESTED** [review]
its not ordered by best, its ordered by time

**Comment by JustDoom** [comment]
you have let me down nDreamBerd

**Comment by YouHaveTrouble** [comment]
https://www.youtube.com/watch?v=ML_cmmCcT9s moment

**Review by YouHaveTrouble — APPROVED** [review]
lgtm

**Comment by JustDoom** [comment]
@TodePond done

**Review by TodePond — DISMISSED** [review]
lgtm just need to fix merge conflict

**Pull request merged**
